using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    void Update()
    {

        // transform‚ğæ“¾
        Transform myTransform = this.transform;

        // À•W‚ğæ“¾
        Vector3 pos = myTransform.position;
        pos.y += 0.048f;    // yÀ•W‚Ö0.01‰ÁZ

        if (GameManager.score >= 100000)
        {
            pos.y += 0.012f;
        }
        if (GameManager.score >= 1000000)
        {
            pos.y += 0.024f;
        }
        if (GameManager.score >= 5000000)
        {
            pos.y += 0.036f;
        }
        if (GameManager.score >= 10000000)
        {
            pos.y += 0.006f;
        }

        myTransform.position = pos;  // À•W‚ğİ’è
    }
}