using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;


public class NewBehaviourScript2 : MonoBehaviour
{
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.collider.CompareTag("Player"))
        {
                // transform‚ğæ“¾
                Transform myTransform = this.transform;

                // À•W‚ğæ“¾
                Vector3 pos = myTransform.position;
                pos.x = 10000.0f;    // yÀ•W‚Ö0.01‰ÁZ

                myTransform.position = pos;  // À•W‚ğİ’è
            //Time.timeScale = 0;
        }
    }

}
